// GlowFunFactory_V2 ABI
export const FACTORY_ABI = [
  // ── View functions ────────────────────────────────────────────────────────
  { name: 'VERSION',            type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'launchedTokensCount', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'launchedTokens',     type: 'function', stateMutability: 'view', inputs: [{ name: 'index', type: 'uint256' }], outputs: [{ type: 'address' }] },
  // getTokensPaginated does NOT exist in the deployed bytecode — use launchedTokens(index) loop instead
  { name: 'isLaunchedToken',    type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'bool' }] },
  { name: 'getTokenState',      type: 'function', stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'creator',                   type: 'address' },
      { name: 'virtualUsdcReserves',       type: 'uint256' },
      { name: 'virtualTokenReserves',      type: 'uint256' },
      { name: 'realUsdcRaised',            type: 'uint256' },
      { name: 'realTokensSold',            type: 'uint256' },
      { name: 'graduated',                 type: 'bool'    },
      { name: 'createdAt',                 type: 'uint256' },
      { name: 'curveTokens',               type: 'uint256' },
      { name: 'graduationTokens',          type: 'uint256' },
      { name: 'creatorTokens',             type: 'uint256' },
      { name: 'totalSupply',               type: 'uint256' },
      { name: 'tokenGraduationThreshold',  type: 'uint256' },
      { name: 'creatorTokensLocked',       type: 'bool'    },
      { name: 'creatorLockExpiry',         type: 'uint256' },
    ]}] },
  { name: 'tokenStates', type: 'function', stateMutability: 'view',
    inputs: [{ type: 'address' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'creator',                   type: 'address' },
      { name: 'virtualUsdcReserves',       type: 'uint256' },
      { name: 'virtualTokenReserves',      type: 'uint256' },
      { name: 'realUsdcRaised',            type: 'uint256' },
      { name: 'realTokensSold',            type: 'uint256' },
      { name: 'graduated',                 type: 'bool'    },
      { name: 'createdAt',                 type: 'uint256' },
      { name: 'curveTokens',               type: 'uint256' },
      { name: 'graduationTokens',          type: 'uint256' },
      { name: 'creatorTokens',             type: 'uint256' },
      { name: 'totalSupply',               type: 'uint256' },
      { name: 'tokenGraduationThreshold',  type: 'uint256' },
      { name: 'creatorTokensLocked',       type: 'bool'    },
      { name: 'creatorLockExpiry',         type: 'uint256' },
    ]}] },
  { name: 'getTokenPrice',   type: 'function', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'getBuyQuote',     type: 'function', stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }, { name: 'usdcIn', type: 'uint256' }],
    outputs: [{ type: 'uint256' }] },
  { name: 'getSellQuote',    type: 'function', stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }, { name: 'tokensIn', type: 'uint256' }],
    outputs: [{ type: 'uint256' }] },
  { name: 'getMarketCap',    type: 'function', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'getProgress',     type: 'function', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'isCreatorLocked', type: 'function', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ type: 'bool' }] },
  // V2: config read via individual public state vars (getConfig removed)

  // Config state
  { name: 'usdc',                     type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { name: 'feeRecipient',             type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { name: 'graduationRecipient',      type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { name: 'graduationThreshold',      type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'protocolFeeBps',           type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'creationFee',              type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'creatorGraduationFeeBps',  type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'referralFeeBps',           type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'antiSnipeDuration',        type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'antiSnipeTaxBps',          type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'maxBuyBps',                type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'buyCooldown',              type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'creatorLockDuration',      type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'perTokenGraduationFeeBps', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'kingOfHill',               type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { name: 'kingOfHillRaised',         type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'paused',                   type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'bool' }] },
  { name: 'pausedAt',                 type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'pendingFeeRecipient',      type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { name: 'pendingGraduationRecipient', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'address' }] },
  { name: 'blacklistedTokens',        type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'bool' }] },
  { name: 'blacklistedWallets',       type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'bool' }] },
  { name: 'referralEarnings',         type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'pendingGraduationUsdc',    type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'pendingGraduationTokens',  type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'pendingCreatorGraduationUsdc', type: 'function', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'lastBuyTime',             type: 'function', stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }, { name: 'wallet', type: 'address' }],
    outputs: [{ type: 'uint256' }] },

  // ── State-changing functions ───────────────────────────────────────────────
  { name: 'launchToken', type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'p', type: 'tuple', components: [
      { name: 'name',                    type: 'string'  },
      { name: 'symbol',                  type: 'string'  },
      { name: 'description',             type: 'string'  },
      { name: 'imageUri',                type: 'string'  },
      { name: 'twitter',                 type: 'string'  },
      { name: 'telegram',                type: 'string'  },
      { name: 'website',                 type: 'string'  },
      { name: 'totalSupply',             type: 'uint256' },
      { name: 'curveAllocationBps',      type: 'uint256' },
      { name: 'creatorAllocationBps',    type: 'uint256' },
      { name: 'graduationThresholdUsdc', type: 'uint256' },
      { name: 'initialLiquidityUsdc',   type: 'uint256' },
    ]}],
    outputs: [{ name: 'token', type: 'address' }] },

  { name: 'buyTokens', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'token',        type: 'address' },
      { name: 'minTokensOut', type: 'uint256' },
      { name: 'referrer',     type: 'address' },
    ],
    outputs: [{ name: 'usdcIn', type: 'uint256' }, { name: 'tokensOut', type: 'uint256' }] },

  { name: 'sellTokens', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'token',      type: 'address' },
      { name: 'tokensIn',   type: 'uint256' },
      { name: 'minUsdcOut', type: 'uint256' },
    ],
    outputs: [] },

  { name: 'claimGraduation',        type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [] },
  { name: 'claimCreatorGraduation', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [] },
  { name: 'forceGraduate',          type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [] },
  { name: 'creatorForceGraduate',   type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [] },
  { name: 'claimReferral', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'updateTokenMetadata', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: '_imageUri', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_twitter', type: 'string' },
      { name: '_telegram', type: 'string' },
      { name: '_website', type: 'string' },
    ], outputs: [] },
  { name: 'unlockCreatorTokens',    type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [] },

  // ── Admin ─────────────────────────────────────────────────────────────────
  { name: 'updateConfig', type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 's', type: 'tuple', components: [
      { name: 'graduationThreshold',     type: 'uint256' },
      { name: 'protocolFeeBps',          type: 'uint256' },
      { name: 'creationFee',             type: 'uint256' },
      { name: 'creatorGraduationFeeBps', type: 'uint256' },
      { name: 'referralFeeBps',          type: 'uint256' },
      { name: 'antiSnipeDuration',       type: 'uint256' },
      { name: 'antiSnipeTaxBps',         type: 'uint256' },
      { name: 'maxBuyBps',               type: 'uint256' },
      { name: 'buyCooldown',             type: 'uint256' },
      { name: 'creatorLockDuration',     type: 'uint256' },
      { name: 'perTokenGraduationFeeBps', type: 'uint256' },
    ]}],
    outputs: [] },
  { name: 'setProtocolFeeBps',           type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'bps', type: 'uint256' }], outputs: [] },
  { name: 'setCreationFee',              type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'fee', type: 'uint256' }], outputs: [] },
  { name: 'setGraduationThreshold',      type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'threshold', type: 'uint256' }], outputs: [] },
  { name: 'setCreatorGraduationFeeBps',  type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'bps', type: 'uint256' }], outputs: [] },
  { name: 'setReferralFeeBps',           type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'bps', type: 'uint256' }], outputs: [] },
  { name: 'setAntiSnipeConfig',          type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'duration', type: 'uint256' }, { name: 'taxBps', type: 'uint256' }], outputs: [] },
  { name: 'setMaxBuyBps',                type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'bps', type: 'uint256' }], outputs: [] },
  { name: 'setBuyCooldown',              type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'seconds_', type: 'uint256' }], outputs: [] },
  { name: 'setCreatorLockDuration',      type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'seconds_', type: 'uint256' }], outputs: [] },
  { name: 'setPerTokenGraduationFeeBps', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'bps', type: 'uint256' }], outputs: [] },
  { name: 'proposeFeeRecipient',         type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'recipient', type: 'address' }], outputs: [] },
  { name: 'acceptFeeRecipient',          type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'proposeGraduationRecipient',  type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'recipient', type: 'address' }], outputs: [] },
  { name: 'acceptGraduationRecipient',   type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'blacklistToken',              type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }, { name: 'bl', type: 'bool' }], outputs: [] },
  { name: 'blacklistWallet',             type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'wallet', type: 'address' }, { name: 'bl', type: 'bool' }], outputs: [] },
  { name: 'pause',                       type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'unpause',                     type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'emergencyUnpause',            type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },

  // ── Events ────────────────────────────────────────────────────────────────
  { name: 'TokenLaunched',   type: 'event', inputs: [
    { name: 'token',              type: 'address', indexed: true  },
    { name: 'creator',            type: 'address', indexed: true  },
    { name: 'name',               type: 'string',  indexed: false },
    { name: 'symbol',             type: 'string',  indexed: false },
    { name: 'totalSupply',        type: 'uint256', indexed: false },
    { name: 'curveTokens',        type: 'uint256', indexed: false },
    { name: 'graduationTokens',   type: 'uint256', indexed: false },
    { name: 'creatorTokens',      type: 'uint256', indexed: false },
    { name: 'graduationThreshold',type: 'uint256', indexed: false },
    { name: 'timestamp',          type: 'uint256', indexed: false },
  ]},
  { name: 'TokensBought', type: 'event', inputs: [
    { name: 'token',             type: 'address', indexed: true  },
    { name: 'buyer',             type: 'address', indexed: true  },
    { name: 'referrer',          type: 'address', indexed: true  },
    { name: 'usdcIn',            type: 'uint256', indexed: false },
    { name: 'tokensOut',         type: 'uint256', indexed: false },
    { name: 'price',             type: 'uint256', indexed: false },
    { name: 'protocolFee',       type: 'uint256', indexed: false },
    { name: 'referralFee',       type: 'uint256', indexed: false },
    { name: 'antiSnipeFee',      type: 'uint256', indexed: false },
    { name: 'newRealUsdcRaised', type: 'uint256', indexed: false },
    { name: 'timestamp',         type: 'uint256', indexed: false },
  ]},
  { name: 'TokensSold', type: 'event', inputs: [
    { name: 'token',             type: 'address', indexed: true  },
    { name: 'seller',            type: 'address', indexed: true  },
    { name: 'tokensIn',          type: 'uint256', indexed: false },
    { name: 'usdcOut',           type: 'uint256', indexed: false },
    { name: 'price',             type: 'uint256', indexed: false },
    { name: 'protocolFee',       type: 'uint256', indexed: false },
    { name: 'newRealUsdcRaised', type: 'uint256', indexed: false },
    { name: 'timestamp',         type: 'uint256', indexed: false },
  ]},
  { name: 'TokenGraduated', type: 'event', inputs: [
    { name: 'token',       type: 'address', indexed: true  },
    { name: 'creator',     type: 'address', indexed: true  },
    { name: 'usdcRaised',  type: 'uint256', indexed: false },
    { name: 'tokenAmount', type: 'uint256', indexed: false },
    { name: 'timestamp',   type: 'uint256', indexed: false },
  ]},
  { name: 'MilestoneReached', type: 'event', inputs: [
    { name: 'token',         type: 'address', indexed: true  },
    { name: 'progressBps',   type: 'uint256', indexed: false },
    { name: 'realUsdcRaised',type: 'uint256', indexed: false },
  ]},
  { name: 'KingOfHill', type: 'event', inputs: [
    { name: 'token',       type: 'address', indexed: true  },
    { name: 'usdcRaised',  type: 'uint256', indexed: false },
    { name: 'timestamp',   type: 'uint256', indexed: false },
  ]},
  { name: 'ConfigUpdated', type: 'event', inputs: [] },
  { name: 'ReferralEarned', type: 'event', inputs: [
    { name: 'referrer', type: 'address', indexed: true  },
    { name: 'token',    type: 'address', indexed: true  },
    { name: 'amount',   type: 'uint256', indexed: false },
  ]},

  // ── V3: individual setters (no restrictions, owner-only) ──────────────
  { name: 'setGraduationThreshold',      type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setProtocolFeeBps',           type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setCreationFee',              type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setCreatorGraduationFeeBps', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setReferralFeeBps',           type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setAntiSnipeDuration',        type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setAntiSnipeTaxBps',          type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setMaxBuyBps',                type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setBuyCooldown',              type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setCreatorLockDuration',      type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  { name: 'setPerTokenGraduationFeeBps', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'value', type: 'uint256' }], outputs: [] },
  // V3 updateConfig takes plain args (not struct) — no restrictions
  { name: 'updateConfig', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: '_graduationThreshold',      type: 'uint256' },
      { name: '_protocolFeeBps',           type: 'uint256' },
      { name: '_creationFee',              type: 'uint256' },
      { name: '_creatorGraduationFeeBps',  type: 'uint256' },
      { name: '_referralFeeBps',           type: 'uint256' },
      { name: '_antiSnipeDuration',        type: 'uint256' },
      { name: '_antiSnipeTaxBps',          type: 'uint256' },
      { name: '_maxBuyBps',                type: 'uint256' },
      { name: '_buyCooldown',              type: 'uint256' },
      { name: '_creatorLockDuration',      type: 'uint256' },
      { name: '_perTokenGraduationFeeBps', type: 'uint256' },
    ],
    outputs: [] },
] as const
