export const FACTORY_ABI = [
  // ── Launch ────────────────────────────────────────────────────────────────
  {
    name: 'launchToken',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'p',
        type: 'tuple',
        components: [
          { name: 'name', type: 'string' },
          { name: 'symbol', type: 'string' },
          { name: 'description', type: 'string' },
          { name: 'imageUri', type: 'string' },
          { name: 'twitter', type: 'string' },
          { name: 'telegram', type: 'string' },
          { name: 'website', type: 'string' },
          { name: 'totalSupply', type: 'uint256' },
          { name: 'curveAllocationBps', type: 'uint256' },
          { name: 'creatorAllocationBps', type: 'uint256' },
          { name: 'graduationThresholdUsdc', type: 'uint256' },
        ],
      },
    ],
    outputs: [{ name: 'token', type: 'address' }],
  },

  // ── Trade ─────────────────────────────────────────────────────────────────
  {
    name: 'buyTokens',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'minTokensOut', type: 'uint256' },
    ],
    outputs: [
      { name: 'usdcIn', type: 'uint256' },
      { name: 'tokensOut', type: 'uint256' },
    ],
  },
  {
    name: 'sellTokens',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'tokensIn', type: 'uint256' },
      { name: 'minUsdcOut', type: 'uint256' },
    ],
    outputs: [{ name: 'usdcOutNet', type: 'uint256' }],
  },

  // ── Views ─────────────────────────────────────────────────────────────────
  {
    name: 'getBuyQuote',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'usdcIn', type: 'uint256' },
    ],
    outputs: [{ name: 'tokensOut', type: 'uint256' }],
  },
  {
    name: 'getSellQuote',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'tokensIn', type: 'uint256' },
    ],
    outputs: [{ name: 'usdcOutNet', type: 'uint256' }],
  },
  {
    name: 'getTokenPrice',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'getMarketCap',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: 'marketCapUsdc6', type: 'uint256' }],
  },
  {
    name: 'getProgress',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'getTokenState',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'creator', type: 'address' },
          { name: 'virtualUsdcReserves', type: 'uint256' },
          { name: 'virtualTokenReserves', type: 'uint256' },
          { name: 'realUsdcRaised', type: 'uint256' },
          { name: 'realTokensSold', type: 'uint256' },
          { name: 'graduated', type: 'bool' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'curveTokens', type: 'uint256' },
          { name: 'graduationTokens', type: 'uint256' },
          { name: 'creatorTokens', type: 'uint256' },
          { name: 'totalSupply', type: 'uint256' },
          { name: 'tokenGraduationThreshold', type: 'uint256' },
        ],
      },
    ],
  },
  {
    name: 'allTokens',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    name: 'tokenCount',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'tokenStates',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [
      { name: 'creator', type: 'address' },
      { name: 'virtualUsdcReserves', type: 'uint256' },
      { name: 'virtualTokenReserves', type: 'uint256' },
      { name: 'realUsdcRaised', type: 'uint256' },
      { name: 'realTokensSold', type: 'uint256' },
      { name: 'graduated', type: 'bool' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'curveTokens', type: 'uint256' },
      { name: 'graduationTokens', type: 'uint256' },
      { name: 'creatorTokens', type: 'uint256' },
      { name: 'totalSupply', type: 'uint256' },
      { name: 'tokenGraduationThreshold', type: 'uint256' },
    ],
  },

  // ── Admin ─────────────────────────────────────────────────────────────────
  {
    name: 'setCreationFee',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'fee', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'setProtocolFeeBps',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bps', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'setFeeRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    name: 'setGraduationRecipient',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [],
  },
  {
    name: 'setGraduationThreshold',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'threshold', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'setUsdcAddress',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'usdcAddress', type: 'address' }],
    outputs: [],
  },
  { name: 'pause', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { name: 'unpause', type: 'function', stateMutability: 'nonpayable', inputs: [], outputs: [] },

  // ── State vars ────────────────────────────────────────────────────────────
  { name: 'creationFee', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256' }] },
  { name: 'protocolFeeBps', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256' }] },
  { name: 'graduationThreshold', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256' }] },
  { name: 'feeRecipient', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { name: 'graduationRecipient', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address' }] },
  { name: 'isLaunchedToken', type: 'function', stateMutability: 'view', inputs: [{ name: 'token', type: 'address' }], outputs: [{ name: '', type: 'bool' }] },
  { name: 'paused', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'bool' }] },

  // ── Events ────────────────────────────────────────────────────────────────
  {
    name: 'TokenLaunchedV2',
    type: 'event',
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'creator', type: 'address' },
      { indexed: false, name: 'name', type: 'string' },
      { indexed: false, name: 'symbol', type: 'string' },
      { indexed: false, name: 'totalSupply', type: 'uint256' },
      { indexed: false, name: 'curveTokens', type: 'uint256' },
      { indexed: false, name: 'graduationTokens', type: 'uint256' },
      { indexed: false, name: 'creatorTokens', type: 'uint256' },
      { indexed: false, name: 'graduationThreshold', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
  },
  {
    name: 'TokensBought',
    type: 'event',
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'buyer', type: 'address' },
      { indexed: false, name: 'usdcIn', type: 'uint256' },
      { indexed: false, name: 'tokensOut', type: 'uint256' },
      { indexed: false, name: 'price', type: 'uint256' },
    ],
  },
  {
    name: 'TokensSold',
    type: 'event',
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'seller', type: 'address' },
      { indexed: false, name: 'tokensIn', type: 'uint256' },
      { indexed: false, name: 'usdcOut', type: 'uint256' },
      { indexed: false, name: 'price', type: 'uint256' },
    ],
  },
  {
    name: 'TokenGraduated',
    type: 'event',
    inputs: [
      { indexed: true, name: 'token', type: 'address' },
      { indexed: true, name: 'recipient', type: 'address' },
      { indexed: false, name: 'usdcAmount', type: 'uint256' },
      { indexed: false, name: 'tokenAmount', type: 'uint256' },
      { indexed: false, name: 'timestamp', type: 'uint256' },
    ],
  },
] as const
